/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author E-Bussines14
 */
public class SPP extends javax.swing.JFrame {

    /**
     * Creates new form SPP
     */
    public SPP() {
        initComponents();
        cmbJurusanItemStateChanged(null);
        if(txtSks.getText().length()<1)
        hitung.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        rbD3 = new javax.swing.JRadioButton();
        rbS1 = new javax.swing.JRadioButton();
        txtSks = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttetap = new javax.swing.JTextField();
        txtVar = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        cmbJurusan = new javax.swing.JComboBox();
        btnSimpan = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Jurusan");

        jLabel4.setText("Program");

        jLabel5.setText("SKS");

        buttonGroup1.add(rbD3);
        rbD3.setText("D3");
        rbD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbD3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbS1);
        rbS1.setText("S1");
        rbS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS1ActionPerformed(evt);
            }
        });

        txtSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSksActionPerformed(evt);
            }
        });
        txtSks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSksKeyReleased(evt);
            }
        });

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jLabel6.setText("SPP Tetap");

        jLabel7.setText("SPP Variabel");

        jLabel8.setText("Total");

        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manajemen Informatika", "Teknik Informatika", "Sistem Informasi" }));
        cmbJurusan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbJurusanItemStateChanged(evt);
            }
        });
        cmbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJurusanActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(hitung)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(txtNIM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(txtVar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttetap, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbD3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbS1)
                                .addGap(81, 81, 81))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTampil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addComponent(rbS1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbD3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hitung)
                            .addComponent(btnSimpan)
                            .addComponent(btnTampil)
                            .addComponent(btnHapus)
                            .addComponent(btnEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(txttetap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int spptetap=0, sppvar=0;
        int pil=cmbJurusan.getSelectedIndex();
        if((pil==0) &&(rbD3.isSelected()==true))
        {
            spptetap = 400000;
            sppvar = 27500;
        }
        else if((pil==2) &&(rbD3.isSelected()==true))
        {
            spptetap = 400000;
            sppvar = 27500;
        }else
        if((pil==1) &&(rbS1.isSelected()==true))
        {
            spptetap = 600000;
            sppvar = 30000;
        }else
        if((pil==2) &&(rbS1.isSelected()==true))
        {
            spptetap = 600000;
            sppvar = 30000;
        }
        long total = Integer.valueOf(txtSks.getText().trim()) * sppvar;
        long a = spptetap + total;
        txttetap.setText(String.valueOf(spptetap));
        txtVar.setText(String.valueOf(sppvar));
        txtTotal.setText(String.valueOf(a));
    }//GEN-LAST:event_hitungActionPerformed

    private void cmbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJurusanActionPerformed

    private void cmbJurusanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbJurusanItemStateChanged
        // TODO add your handling code here:
        int pl = cmbJurusan.getSelectedIndex();
        if(pl == 0)
        {
            rbD3.setEnabled(true);
            rbS1.setEnabled(false);            
        }else if(pl == 1)
        {
            rbD3.setEnabled(false);
            rbS1.setEnabled(true);
        }else if(pl == 2)
        {
            rbD3.setEnabled(false);
            rbS1.setEnabled(true);
        }else
        {
            rbD3.setEnabled(true);
            rbS1.setEnabled(true);
        }
    }//GEN-LAST:event_cmbJurusanItemStateChanged

    private void txtSksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSksKeyReleased
        // TODO add your handling code here:
        if(txtSks.getText().length()>0)
        {
            hitung.setEnabled(true);
        }else
        {
            hitung.setEnabled(false);
        }
    }//GEN-LAST:event_txtSksKeyReleased

    private void rbD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbD3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbD3ActionPerformed

    private void rbS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS1ActionPerformed

    private void txtSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSksActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
     Connection conn=null;
     String dbUrl="jdbc:mysql://localhost:3306/dbtaxipayment1101";
     try {
//         String sql = "insert into spp ('"+txtNIM.getText()+"','"+txtNama.getText()+"','"+cmbJurusan.getSelectedItem()+"','"+rbD3.getActionCommand()+"','"+rbS1.getActionCommand()+"''"+txtSks.getText()+"','"+txttetap.getText()+"','"+txtVar.getText()+"','"+txtTotal.getText()+"')";
   
         Class.forName("com.mysql.jdbc.Driver");
         conn=DriverManager.getConnection(dbUrl,"root","");
          System.out.println("Koneksi Sukses");
       String sql = "insert into spp values ('"+txtNIM.getText()+"','"+txtNama.getText()+"','"+cmbJurusan.getSelectedItem()+"','"+txtSks.getText()+"','"+txttetap.getText()+"','"+txtVar.getText()+"','"+txtTotal.getText()+"')";
       PreparedStatement s = conn.prepareStatement(sql);
          s.executeUpdate();
          System.out.println(sql);
                
         
      /*
            txtNIM.setText("");
            txtNama.setText("");
            cmbJurusan.setSelectedItem("");
            rbD3.setActionCommand("");
            rbS1.setActionCommand("");
            txtSks.setText("");
            txttetap.setText("");
            txtVar.setText("");
            txtNIM.requestFocus();*/
            
            JOptionPane.showMessageDialog(null, "Berhasil tambah data");
            conn.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SPP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Data Eror");

            Logger.getLogger(SPP.class.getName()).log(Level.SEVERE, null, ex);
        }

    // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        Connection koneksi=null;
try{
    String url="jdbc:mysql://localhost:3306/dbtaxipayment1101";
    Class.forName("com.mysql.jdbc.Driver");
    koneksi= DriverManager.getConnection(url,"root","");
try{
    String reportName=System.getProperty("user.dir") + "/src/template/laporan/tampil.jasper";
    HashMap parameter = new HashMap();
    File report_file = new File(reportName);

    JasperReport jasperReport = (JasperReport)JRLoader.loadObject(report_file.getPath());
    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
    JasperViewer.viewReport(jasperPrint, false);
    JasperViewer.setDefaultLookAndFeelDecorated(false);
 }catch (Exception e) {
 JOptionPane.showMessageDialog(null, "Data tidak bisa dimunculkan!" + "\n" + e.getMessage()+ "Data telah di Cetak, "+JOptionPane.ERROR_MESSAGE);
 }
    }                                        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(SPP.class.getName()).log(Level.SEVERE, null, ex);
        }        catch (SQLException ex) {
            Logger.getLogger(SPP.class.getName()).log(Level.SEVERE, null, ex);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    Connection conn=null;
   String dbUrl="jdbc:mysql://localhost:3306/dbtaxipayment1101";
   int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
      if (ok==0)
       {
        try
         {
           Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection(dbUrl,"root","");
            String sql="delete from spp where NIM='"+txtNIM.getText()+"'";
            PreparedStatement st=conn.prepareStatement(sql);
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Data Sukses");
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Delete Data Gagal");
        }
       }    // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    Connection conn=null;
   String dbUrl="jdbc:mysql://localhost:3306/dbtaxipayment1101";
     int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
         try
            {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection(dbUrl,"root","");
            String sql="update spp set NIM=?,Nama=?,Jurusan=?,Sks=?,tetap=?,Var=? where NIM='"+txtNIM.getText()+"'";
                PreparedStatement st=conn.prepareStatement(sql);
                st.executeUpdate();
                if(ok==0)
                {
                try
                    {
                        st.setString(1,txtNIM.getText());
                        st.setString(2,txtNama.getText());
                        st.setString(3, (String) cmbJurusan.getSelectedItem());
                        st.setString(4,txtSks.getText());
                        st.setString(5,txttetap.getText());
                        st.setString(6,txtVar.getText());
                        st.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                    }catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
                }
           }catch (Exception e){}        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SPP().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTampil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cmbJurusan;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbD3;
    private javax.swing.JRadioButton rbS1;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSks;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVar;
    private javax.swing.JTextField txttetap;
    // End of variables declaration//GEN-END:variables

    
}
